# Generated by Django 2.0.2 on 2018-02-24 15:12

from django.db import migrations, models
import django.db.models.deletion

#------------ Data Migration ------------#
# It's launcher after table migration with 'migrations.RunPython(forwards_func, reverse_func)'

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version

    #Create the 2
    Camp = apps.get_model("bow", "Camp")
    db_alias = schema_editor.connection.alias
    Camp.objects.using(db_alias).bulk_create([
        Camp(name='Black', description='Ce sont les chevaliers noirs.'),
        Camp(name='White', description='Ce sont les chevaliers blancs.'),
    ])

    Level = apps.get_model("bow", "Level")
    db_alias = schema_editor.connection.alias   #useless and repetitive line?
    Level.objects.using(db_alias).bulk_create([
        Level(name="Apprenti", required_experience=0),
        Level(name="Soldat", required_experience=100),
        Level(name="Champion", required_experience=300),
        Level(name="Maître", required_experience=700),
    ])

    Characters = apps.get_model("bow", "Characters")
    db_alias = schema_editor.connection.alias
    Characters.objects.using(db_alias).bulk_create([
        #Just basic opponents in case that the player is too weak and can't fight anyone
        Characters(name="L'apprenti chevalier noir", strength=5, defense=5, speed=5, agility=5, victories=0, fight_count=0, experience=0, gold=0, camp_id=1, level_id=1),
        Characters(name="L'apprenti chevalier blanc", strength=5, defense=5, speed=5, agility=5, victories=0, fight_count=0, experience=0, gold=0, camp_id=2, level_id=1),
    ])

def reverse_func(apps, schema_editor):
    # forwards_func() creates two Country instances,
    # so reverse_func() should delete them.

    Camp = apps.get_model("bow", "Camp")
    db_alias = schema_editor.connection.alias
    Camp.objects.using(db_alias).filter(name='Black').delete()
    Camp.objects.using(db_alias).filter(name='White').delete()

    Level = apps.get_model("bow", "Level")
    db_alias = schema_editor.connection.alias
    Level.objects.using(db_alias).filter(name='Apprenti').delete()
    Level.objects.using(db_alias).filter(name='Soldat').delete()
    Level.objects.using(db_alias).filter(name='Champion').delete()
    Level.objects.using(db_alias).filter(name='Maître').delete()

    Characters = apps.get_model("bow", "Characters")
    db_alias = schema_editor.connection.alias
    Characters.objects.using(db_alias).filter(name="L'apprenti chevalier blanc").delete()
    Characters.objects.using(db_alias).filter(name="L'apprenti chevalier noir").delete()

#------------ Table migration ------------#

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bow', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
